services:
  Proxy-Client2:
    image: nginx:latest
    container_name: nginx-proxy1 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
    networks:
      - rede-Client2
      - proxy       
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.client2-portal-nginx-router.rule=Host(`portal.client2.dockerson.br`)" 
      - "traefik.http.routers.client2-portal-nginx-router.entrypoints=websecure"
      - "traefik.http.routers.client2-portal-nginx-router.tls=true" 
      
      - "traefik.http.routers.client2-wordpress-nginx-router.rule=Host(`wordpress.client1.dockerson.br`)" 
      - "traefik.http.routers.client2-wordpress-nginx-router.entrypoints=websecure"
      - "traefik.http.routers.client2-wordpress-nginx-router.tls=true" 
    
      - "traefik.http.services.client1-nginx-service.loadbalancer.server.port=80" 
 
 # Portal do Cliente 2
  client2-portal:
    image: nginx:latest
    container_name: client2-portal
    volumes:
      - ./Portal/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - rede-Client2

  # wordpress do Cliente 2
  client2-wordpress:
    image: nginx:latest
    container_name: client2-wordpress
    volumes:
    networks:
      - rede-Client2

networks:
  rede-Client2:
    external: true
  proxy:
    external: true
