services:
  Proxy-Client1:
    image: nginx:latest
    container_name: nginx-proxy1 # Consistent naming (ngix-proxy1 was a typo)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Mount your Nginx config here
    networks:
      - rede-Client1 # If your actual applications are on this network, Nginx should be too
      - proxy       # Nginx MUST be on the 'proxy' network for Traefik to find it
    labels:
      - "traefik.enable=true"

      # Router for portal.client1.dockerson.br
      - "traefik.http.routers.client1-portal-nginx-router.rule=Host(`portal.client1.dockerson.br`)" # Prefer Host() over HostRegexp() for exact matches
      - "traefik.http.routers.client1-portal-nginx-router.entrypoints=websecure"
      - "traefik.http.routers.client1-portal-nginx-router.tls=true" # Ensure TLS is explicitly enabled on the router
      
      # Router for hotsite.client1.dockerson.br
      - "traefik.http.routers.client1-hotsite-nginx-router.rule=Host(`hotsite.client1.dockerson.br`)" # Prefer Host()
      - "traefik.http.routers.client1-hotsite-nginx-router.entrypoints=websecure"
      - "traefik.http.routers.client1-hotsite-nginx-router.tls=true" # Ensure TLS is explicitly enabled on the router
      
      # Define the service Traefik will use to connect to this Nginx container
      # This single service definition can be used by multiple routers
      - "traefik.http.services.client1-nginx-service.loadbalancer.server.port=80" # This tells Traefik Nginx listens on 80 INTERNALLY
 

  client1-portal:
    image: nginx:latest
    container_name: client1-portal
    volumes:
      - ./Portal/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - rede-Client1

  # Hotsite do Cliente 1
  client1-hotsite:
    image: nginx:latest
    container_name: client1-hotsite
    volumes:
      - ./hotsite/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - rede-Client1

networks:
  rede-Client1:
    external: true
  proxy:
    external: true
