services:
  Proxy-client3:
    image: nginx:latest
    container_name: nginx-proxy3 
    restart: unless-stopped
    depends_on:
      - client3-portal
      - client3-wordpress
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
    networks:
      - rede-Client3
      - proxy       
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.client3-portal-nginx-router.rule=Host(`portal.client3.dockerson.br`)" 
      - "traefik.http.routers.client3-portal-nginx-router.entrypoints=websecure"
      - "traefik.http.routers.client3-portal-nginx-router.tls=true" 
      
      - "traefik.http.routers.client3-wordpress-nginx-router.rule=Host(`wordpress.client3.dockerson.br`)" 
      - "traefik.http.routers.client3-wordpress-nginx-router.entrypoints=websecure"
      - "traefik.http.routers.client3-wordpress-nginx-router.tls=true" 
    
      - "traefik.http.services.client3-nginx-service.loadbalancer.server.port=80" 
 
 # Portal do Cliente 2
  client3-portal:
    image: nginx:latest
    container_name: client3-portal
    volumes:
      - ./Portal/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - rede-Client3

  # wordpress do Cliente 2
  client3-wordpress:
    image: wordpress
    restart: always
    container_name: client3-wordpress
    ports:
      - 8084:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress2:/var/www/html
    networks:
      - rede-Client3

  db2:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db2:/var/lib/mysql
    networks:
      - rede-Client3

volumes:
  wordpress2:
  db2:

networks:
  rede-Client3:
    external: true
  proxy:
    external: true
