global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG 
api:
  dashboard: true
  insecure: true 

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true 
  websecure:
    address: :443

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false 

certificatesResolvers: 
  myresolver:
    acme:
      tlsChallenge: {} 
      email: dockerson@dockerson.br 
      storage: /letsencrypt/acme.json
      # For testing, uncomment the staging server below:
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory

