# traefik.yml (Static Configuration)
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true 
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false # Or true, depending on your setup
  file:
    filename: /etc/traefik/dynamic_config.yaml # Path to your dynamic config file
    watch: true # Traefik will reload if this file changes

global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG 
api:
  dashboard: true
  insecure: true # Only for local dev, disable in production
